name: ccls
base: core24
version: "0.20241108"
summary: C/C++/ObjC Language Server
description: |
  ccls is a C/C++/Objective-C language server.

  Features:
    * Code completion (with both signature help and snippets)
    * Definition/references, and other cross references
    * Cross reference extensions: $ccls/call $ccls/inheritance $ccls/member $ccls/vars ...
    * Formatting
    * Hierarchies: call (caller/callee) hierarchy, inheritance (base/derived) hierarchy, member hierarchy
    * Symbol rename
    * Document symbols and approximate search of workspace symbol
    * Hover information
    * Diagnostics and code actions (clang FixIts)
    * Semantic highlighting and preprocessor skipped regions
    * Semantic navigation: $ccls/navigate

  It has a global view of the code base and support a lot of cross
  reference features, see wiki/FAQ. It starts indexing the whole project
  (including subprojects if exist) parallelly when you open the first file,
  while the main thread can serve requests before the indexing is
  complete. Saving files will incrementally update the index.

grade: stable
confinement: classic
license: Apache-2.0

apps:
  ccls:
    command: usr/bin/ccls
    # not sure why this is needed since snapcraft is setting RPATH on the ccls
    # binary via enable-patchelf below but it seems it still can't find libxml2
    # otherwise so set this explicitly
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR

parts:
  ccls:
    plugin: cmake
    source: https://github.com/MaskRay/ccls.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-attributes:
      - enable-patchelf
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH=/usr/lib/llvm-18
      - -DLLVM_INCLUDE_DIR=/usr/lib/llvm-18/include
    override-build: |
      sed -i "s/\${CLANG_RESOURCE_DIR}/\/snap\/ccls\/current\/\${CLANG_RESOURCE_DIR}/" ../src/CMakeLists.txt
      snapcraftctl build
    build-packages:
      - rapidjson-dev
      - llvm-18-dev
      - libclang-18-dev
      - clang-18
      - zlib1g-dev
    stage-packages:
      - libllvm18
      - libclang-common-18-dev
      - libclang-cpp18
